# Import Libraries

In [3]:
#Required Libraries Input
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure
from termcolor import colored

# Data Calling

In [4]:
#Data Input from same directory
normal = pd.read_csv("1NormalWave.csv", encoding='cp949')
fuzz = pd.read_csv("21FuzzWave.csv", encoding='cp949')
dos = pd.read_csv("3DoSWave.csv", encoding='cp949')
replay = pd.read_csv("4ReplayWave.csv", encoding='cp949')

In [5]:
print("Normal: ", len(normal))
print("Fuzz: ", len(fuzz))
print("DoS: ", len(dos))
print("Replay: ", len(replay))

Normal:  230092
Fuzz:  234483
DoS:  185425
Replay:  50000


In [6]:
# Data Input from same different directory
Car_Data_Frame = pd.read_csv('C:/Users/Lisa/Rezanur/Car Id/tesla 2.trc', encoding='cp949')
Car_Data_Frame

CAN_Data
0             1)         8.4  Rx         0118  8  57 0...
1             2)         8.6  Rx         0343  8  00 9...
2             3)         8.9  Rx         07D5  8  32 0...
3             4)         9.4  Rx         02C2  8  55 5...
4             5)        10.4  Rx         03C2  8  29 5...
...                                                   ...
248676   248677)    218185.6  Rx         0545  8  76 0...
248677   248678)    218186.3  Rx         04E2  8  00 8...
248678   248679)    218186.6  Rx         02E5  8  00 0...
248679   248680)    218186.8  Rx         01D8  8  21 0...
248680   248681)    218187.1  Rx         01CF  8  01 0...

[248681 rows x 1 columns]

In [7]:
#Data call from online
Data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv", encoding='cp949')
Data

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [8]:
#Data Cleaning
#Spliting time and payload
Car_Data_Frame = Car_Data_Frame['CAN_Data'].str.split('Rx         ',n=1,expand=True)
Car_Data_Frame = Car_Data_Frame.rename(columns={0:'Time', 1:'Payload'})

#Splitting Time
Car_Data_Frame_Time = Car_Data_Frame['Time'].str.split(')',n=2,expand=True)
Car_Data_Frame_Time = Car_Data_Frame_Time.rename(columns={0:'Serial', 1:'Time'})
Car_Data_Frame_Time = Car_Data_Frame_Time.Time.astype(float)
Car_Data_Frame_Time = pd.DataFrame(Car_Data_Frame_Time).rename(columns={0:'Time'})

#Splitting Payload
Car_Data_Frame_Time_ID = Car_Data_Frame['Payload'].str.split('  ',n=2,expand=True)
Car_Data_Frame_Time_ID = Car_Data_Frame_Time_ID.rename(columns={0:'CAN_ID', 1:'DLC', 2:'Payload_8_hex'})

#Splitting Payload with each PID
Car_Data_Frame_Time_Payload_hex = Car_Data_Frame_Time_ID['Payload_8_hex'].str.split(' ',n=7,expand=True)
Car_Data_Frame_Time_Payload_hex = Car_Data_Frame_Time_Payload_hex.rename(
    columns={0:'One', 1:'Two', 2:'Three', 3:'Four', 4:'Five', 5:'Six', 6:'Seven', 7:'Eight'})

#Joind all data set
Car_Data_Frame = pd.concat([pd.DataFrame(Car_Data_Frame_Time), pd.DataFrame(Car_Data_Frame_Time_ID), 
                            pd.DataFrame(Car_Data_Frame_Time_Payload_hex)], axis=1)
Car_Data_Frame = Car_Data_Frame.sort_values(['Time'], ignore_index = True)

#Time Gap Calculation (Full_Data_Time_Gap)
Time_gap = [0]
k4 = 1
lenth = len(Car_Data_Frame)-1

for k in Car_Data_Frame.Time:
    k2 = float(Car_Data_Frame.Time[k4]) - float(k)
    Time_gap.append(k2)
    if k4 >= lenth:
        break
    k4 = k4 + 1

#Joind with time gap
Car_Data_Frame = pd.concat([pd.DataFrame(Car_Data_Frame), pd.DataFrame(Time_gap)], axis=1)
Normal_Car_Data_Frame = Car_Data_Frame.rename(columns={0:'Full_Data_Time_Gap'})
print(colored('Total Amount of Data Normal: ', 'blue', attrs=['bold']),len(Car_Data_Frame))

Total Amount of Data Normal:  248681


In [9]:
Normal_Car_Data_Frame

Time CAN_ID DLC             Payload_8_hex One Two Three Four Five  \
0            8.4   0118   8  57 04 22 18 00 00 00 00   57  04    22   18   00   
1            8.6   0343   8  00 90 68 BE 96 00 00 00   00  90    68   BE   96   
2            8.9   07D5   8  32 0E 04 00 00 00 00 00   32  0E    04   00   00   
3            9.4   02C2   8  55 5B A9 B6 02 00 92 00   55  5B    A9   B6   02   
4           10.4   03C2   8  29 55 00 00 00 00 00 00   29  55    00   00   00   
...          ...    ...  ..                       ...  ..  ..   ...  ...  ...   
248676  218185.6   0545   8  76 00 53 E0 98 95 C9 E9   76  00    53   E0   98   
248677  218186.3   04E2   8  00 8C 02 00 00 00 08 00   00  8C    02   00   00   
248678  218186.6   02E5   8  00 00 03 0D 00 00 DD 00   00  00    03   0D   00   
248679  218186.8   01D8   8  21 00 00 00 00 00 40 3A   21  00    00   00   00   
248680  218187.1   01CF   8  01 00 00 00 00 00 40 11   01  00    00   00   00   

       Six Seven Eight  Full_Data_Time_Gap  
0       00    00   00                  0.0  
1       00    00   00                  0.2  
2       00    00   00                  0.3  
3       00    92   00                  0.5  
4       00    00   00                  1.0  
...     ..   ...   ...                 ...  
248676  95    C9   E9                  0.2  
248677  00    08   00                  0.7  
248678  00    DD   00                  0.3  
248679  00    40   3A                  0.2  
248680  00    40   11                  0.3  

[248681 rows x 13 columns]

In [14]:
list(Normal_Car_Data_Frame.columns)

['Time',
 'CAN_ID',
 'DLC',
 'Payload_8_hex',
 'One',
 'Two',
 'Three',
 'Four',
 'Five',
 'Six',
 'Seven',
 'Eight',
 'Full_Data_Time_Gap']

In [10]:
categorical_data = Normal_Car_Data_Frame[['One','Two','Three', 'Four', 
                                          'Five', 'Six', 'Seven', 'Eight']] #Selecting the columns
categorical_data

One Two Three Four Five Six Seven Eight
0       57  04    22   18   00  00    00   00 
1       00  90    68   BE   96  00    00   00 
2       32  0E    04   00   00  00    00   00 
3       55  5B    A9   B6   02  00    92   00 
4       29  55    00   00   00  00    00   00 
...     ..  ..   ...  ...  ...  ..   ...   ...
248676  76  00    53   E0   98  95    C9   E9 
248677  00  8C    02   00   00  00    08   00 
248678  00  00    03   0D   00  00    DD   00 
248679  21  00    00   00   00  00    40   3A 
248680  01  00    00   00   00  00    40   11 

[248681 rows x 8 columns]

# Data Joining

In [15]:
#Data joining
Final = pd.concat([pd.DataFrame(normal), pd.DataFrame(fuzz),
                        pd.DataFrame(dos), pd.DataFrame(replay)], 
                        ignore_index=True ) #Join data in x axis

print('Full Data Shape :', Final.shape)
Final

Full Data Shape : (700000, 12)


Col_0      Col_1       Col_2       Col_3       Col_4       Col_5  \
0       238.50000  300.50000   36.999996 -201.500000   72.500000    0.000000   
1       109.49999  185.50000   97.499990   65.499990  151.500000  -77.499990   
2       320.00000  300.50000  169.999980  -57.000015   72.500000  -92.999985   
3       217.50000  300.50000   95.500000  -95.500000   72.500000  -26.500000   
4       388.50000  300.50000  171.500000 -110.500000   72.500000 -106.500000   
...           ...        ...         ...         ...         ...         ...   
699995  288.00000  248.49998  165.999980  -25.000015   60.499985  -96.999985   
699996  280.50000  248.49998  166.499980  -16.500015   60.499985  -97.499985   
699997  385.00000  248.49998  168.499980  -97.000015   60.499985 -119.499985   
699998  349.50000  183.00000  139.500000  -90.500000   -4.000000 -119.500000   
699999  272.00000   95.50000  131.500000  -30.000000   29.499996 -110.500000   

             Col_6       Col_7       Col_8      Col_9     Col_10  Label  
0        -7.778174  -50.911682   98.287840  82.024380   7.778174      0  
1      -123.743680  -25.455845  112.429970  21.213203  14.142136      0  
2      -111.015760   38.890870   98.287840  82.024380 -20.506096      0  
3       -22.627415 -139.300030   98.287840  82.024380 -14.849243      0  
4      -138.592930   -9.192383   98.287840  82.024380 -12.020815      0  
...            ...         ...         ...        ...        ...    ...  
699995 -111.015760   41.719307  139.300030  67.882250 -26.162949      3  
699996 -111.722870   54.447227  139.300030  67.882250 -26.162949      3  
699997 -156.977700  -21.213196  139.300030  67.882250 -12.020816      3  
699998 -177.483800    8.485291   48.790363  67.175140   8.485281      3  
699999 -164.048770  100.409164   88.388340 -18.384777   7.778174      3  

[700000 rows x 12 columns]

In [16]:
'''https://pandas.pydata.org/docs/reference/api/pandas.concat.html''' ### For Data join details

'https://pandas.pydata.org/docs/reference/api/pandas.concat.html'

In [17]:
pd.concat([pd.DataFrame(normal), pd.DataFrame(fuzz)], ignore_index=True, axis=1) #Join data in y axis

0      1           2           3      4           5   \
0       238.50000  300.5   36.999996 -201.500000   72.5    0.000000   
1       109.49999  185.5   97.499990   65.499990  151.5  -77.499990   
2       320.00000  300.5  169.999980  -57.000015   72.5  -92.999985   
3       217.50000  300.5   95.500000  -95.500000   72.5  -26.500000   
4       388.50000  300.5  171.500000 -110.500000   72.5 -106.500000   
...           ...    ...         ...         ...    ...         ...   
234478        NaN    NaN         NaN         NaN    NaN         NaN   
234479        NaN    NaN         NaN         NaN    NaN         NaN   
234480        NaN    NaN         NaN         NaN    NaN         NaN   
234481        NaN    NaN         NaN         NaN    NaN         NaN   
234482        NaN    NaN         NaN         NaN    NaN         NaN   

                6           7          8          9   ...          14  \
0        -7.778174  -50.911682   98.28784  82.024380  ...  627.500000   
1      -123.743680  -25.455845  112.42997  21.213203  ...   28.999998   
2      -111.015760   38.890870   98.28784  82.024380  ...   28.999998   
3       -22.627415 -139.300030   98.28784  82.024380  ...   28.999998   
4      -138.592930   -9.192383   98.28784  82.024380  ...   28.999998   
...            ...         ...        ...        ...  ...         ...   
234478         NaN         NaN        NaN        NaN  ...  537.500000   
234479         NaN         NaN        NaN        NaN  ...  537.500000   
234480         NaN         NaN        NaN        NaN  ...  537.500000   
234481         NaN         NaN        NaN        NaN  ...  537.500000   
234482         NaN         NaN        NaN        NaN  ...  537.500000   

                15         16         17         18          19         20  \
0       111.000015 -82.499985   2.500000  86.974150   68.589355 -96.873634   
1      -155.499980  -1.500008 -18.999998 -33.941124 -105.358910  36.769547   
2      -155.499980  -1.500008 -18.999998 -33.941124 -105.358910  36.769547   
3      -155.499980  -1.500008 -18.999998 -33.941124 -105.358910  36.769547   
4      -155.499980  -1.500008 -18.999998 -33.941124 -105.358910  36.769547   
...            ...        ...        ...        ...         ...        ...   
234478  102.499970  19.500002  18.500030  91.216780 -117.379730 -71.417786   
234479  102.499970  19.500002  18.500030  91.216780 -117.379730 -71.417786   
234480  102.499970  19.500002  18.500030  91.216780 -117.379730 -71.417786   
234481  102.499970  19.500002  18.500030  91.216780 -117.379730 -71.417786   
234482  102.499970  19.500002  18.500030  91.216780 -117.379730 -71.417786   

               21         22  23  
0        0.000000 -83.438614   1  
1      -74.246216   7.071068   1  
2      -74.246216   7.071068   1  
3      -74.246216   7.071068   1  
4      -74.246216   7.071068   1  
...           ...        ...  ..  
234478 -36.769550 -65.053830   1  
234479 -36.769550 -65.053830   1  
234480 -36.769550 -65.053830   1  
234481 -36.769550 -65.053830   1  
234482 -36.769550 -65.053830   1  

[234483 rows x 24 columns]

In [18]:
print("Normal Data Length :", len(pd.DataFrame(normal)))
print("Fuzz Data Length :", len(pd.DataFrame(fuzz)))

Normal Data Length : 230092
Fuzz Data Length : 234483


In [19]:
#Convert Into Array [Personal Choise]
Final = np.array(Final)
Final

array([[238.5      , 300.5      ,  36.999996 , ...,  82.02438  ,
          7.7781744,   0.       ],
       [109.49999  , 185.5      ,  97.49999  , ...,  21.213203 ,
         14.142136 ,   0.       ],
       [320.       , 300.5      , 169.99998  , ...,  82.02438  ,
        -20.506096 ,   0.       ],
       ...,
       [385.       , 248.49998  , 168.49998  , ...,  67.88225  ,
        -12.020816 ,   3.       ],
       [349.5      , 183.       , 139.5      , ...,  67.17514  ,
          8.485281 ,   3.       ],
       [272.       ,  95.5      , 131.5      , ..., -18.384777 ,
          7.7781744,   3.       ]])

# Data Reshaping

In [20]:
#2D data
print("Final Data Shape :", Final.shape) #Full Shape and saying the dimention here is 2d
print("Final Data Number of Rows :", Final.shape[0]) #Dimension 1 representing data length
print("Final Data Number of Columns :", Final.shape[1]) #Dimension 2 representing number of data feature

Final Data Shape : (700000, 12)
Final Data Number of Rows : 700000
Final Data Number of Columns : 12


In [21]:
#Reshapeing Data into 3D
RearrangeData = Final.reshape(70,10000,12) #Reshaping Rule [10000*70=700000]
shuffle_idx = np.random.permutation(RearrangeData.shape[0]) #Shuffle parameter fixing
RearrangeData = RearrangeData[shuffle_idx] #Shuffling

In [22]:
#Home Work
array = np.array([[1,2,3,4,5,6,7,8]])
###Convert it into 2d,3d,4d?

In [23]:
#Return Into Same Shape 
print('Old:', RearrangeData.shape)
RearrangeData = RearrangeData.reshape(700000, 12)
print('Updated:',RearrangeData.shape)

Old: (70, 10000, 12)
Updated: (700000, 12)


# Data Scaling

In [28]:
#Data normalization by scalling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1, 1)) #Scalling maximun value will 1 and minimum will -1
Final_DataFrame_scaled = scaler.fit_transform(RearrangeData[:,:11]) #Selecting input data set without label column
Final_DataFrame_scaled.shape

(700000, 11)

# Categorical Value Processing

In [27]:
cat_df = pd.DataFrame(['A','B','C','D','E','F','G','H'], columns=['Column'])
print("Data Frame: \n", cat_df)
print('\n')
cat_array = np.array(['A','B','C','D','E','F','G','H'])
print("Array: ", cat_array)

Data Frame: 
   Column
0      A
1      B
2      C
3      D
4      E
5      F
6      G
7      H


Array:  ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']


In [30]:
#Cettegorical Value transfer into Number
from sklearn.preprocessing import LabelEncoder

labelecoder_df = LabelEncoder() #Calling Label Encoder
replay_scaled = pd.DataFrame(cat_df).apply(LabelEncoder().fit_transform) #Applying
replay_scaled = np.array(replay_scaled) #Converting into array
replay_scaled = replay_scaled.astype(np.float32) #Converting into float
replay_scaled

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.]], dtype=float32)

In [31]:
#Cettegorical Value transfer into Number
from sklearn.preprocessing import LabelEncoder

labelecoder_df = LabelEncoder()
replay_scaled = pd.DataFrame(cat_array).apply(LabelEncoder().fit_transform)
replay_scaled = np.array(replay_scaled)
replay_scaled = replay_scaled.astype(np.float32)
replay_scaled

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.]], dtype=float32)

In [32]:
#Cettegorical Value transfer into Number
from sklearn.preprocessing import LabelEncoder

labelecoder_df = LabelEncoder()
replay_scaled = pd.DataFrame(categorical_data).apply(LabelEncoder().fit_transform)
replay_scaled = np.array(replay_scaled)
replay_scaled = replay_scaled.astype(np.float32)
replay_scaled

array([[ 87.,   5.,  35., ...,   1.,   1.,   1.],
       [  0., 145., 105., ...,   1.,   1.,   1.],
       [ 50.,  15.,   5., ...,   1.,   1.,   1.],
       ...,
       [  0.,   1.,   4., ...,   1., 220.,   1.],
       [ 33.,   1.,   1., ...,   1.,  65.,  59.],
       [  1.,   1.,   1., ...,   1.,  65.,  18.]], dtype=float32)